-- データベース作成
CREATE DATABASE IF NOT EXISTS SYCS_users
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE SYCS_users;

-- ユーザー
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

